In [44]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

In [45]:
provider_tsv = 'data/Medicare_Provider_Utilization_and_Payment_Data__Physician_and_Other_Supplier_PUF_CY2017 (1).tsv'
providers = pd.read_csv(provider_tsv, sep='\t',low_memory=False)
providers.head()

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99217,Hospital observation care discharge,N,100.0,96,100,73.398800,325.780000,56.827200,57.492400
1,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99218,Hospital observation care typically 30 minutes,N,26.0,25,26,100.080000,449.000000,78.460000,79.306154
2,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99219,Hospital observation care typically 50 minutes,N,52.0,51,52,136.380000,614.000000,102.807692,103.895385
3,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99220,Hospital observation care typically 70 minutes...,N,59.0,59,59,190.363729,755.932203,141.293559,142.865763
4,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99221,"Initial hospital inpatient care, typically 30 ...",N,16.0,16,16,101.680000,462.812500,79.710000,80.750000

In [46]:
outpatient_csv = 'data/Provider_Outpatient_Hospital_Charge_Data_by_APC__CY2017.csv'
outpatient = pd.read_csv(outpatient_csv)
outpatient.head()

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [47]:
classification_excel = 'data/2020_january_web_addendum_b.12312019.xlsx'
classifications = pd.read_excel(classification_excel)
classifications.head()

,Unnamed: 0,Addendum B.-Final OPPS Payment by HCPCS Code for CY 2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,CPT codes and descriptions only are copyright ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCPCS Code,Short Descriptor,SI,APC,Relative Weight,Payment Rate,National Unadjusted Copayment,Minimum Unadjusted Copayment,Note: Actual copayments would be lower due to ...,* Indicates a Change
2,00100,Anesth salivary gland,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00102,Anesth repair of cleft lip,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00103,Anesth blepharoplasty,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
cbsa_excel = 'data/ZIP_CBSA_032020.xlsx'
cbsa = pd.read_excel(cbsa_excel)
cbsa.head()

   ZIP   CBSA  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  501  35620        0.0        1.0        0.0        1.0
1  601  38660        1.0        1.0        1.0        1.0
2  602  10380        1.0        1.0        1.0        1.0
3  603  10380        1.0        1.0        1.0        1.0
4  604  10380        1.0        1.0        1.0        1.0

In [49]:
# column names contain newline characters, remove them
# also convert spaces to underscores and make lowercase
outpatient.columns = outpatient.columns.str.replace('\n', '_').str.replace(' ', '_').str.lower()
providers.columns = providers.columns.str.replace(' ', '_').str.lower()
classifications.columns = classifications.columns.str.replace(' ', '_').str.lower()
cbsa.columns = cbsa.columns.str.replace(' ', '_').str.lower()

In [50]:
providers.head()

,national_provider_identifier,last_name/organization_name_of_the_provider,first_name_of_the_provider,middle_initial_of_the_provider,credentials_of_the_provider,gender_of_the_provider,entity_type_of_the_provider,street_address_1_of_the_provider,street_address_2_of_the_provider,city_of_the_provider,...,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary/per_day_services,average_medicare_allowed_amount,average_submitted_charge_amount,average_medicare_payment_amount,average_medicare_standardized_amount
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99217,Hospital observation care discharge,N,100.0,96,100,73.398800,325.780000,56.827200,57.492400
1,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99218,Hospital observation care typically 30 minutes,N,26.0,25,26,100.080000,449.000000,78.460000,79.306154
2,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99219,Hospital observation care typically 50 minutes,N,52.0,51,52,136.380000,614.000000,102.807692,103.895385
3,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99220,Hospital observation care typically 70 minutes...,N,59.0,59,59,190.363729,755.932203,141.293559,142.865763
4,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99221,"Initial hospital inpatient care, typically 30 ...",N,16.0,16,16,101.680000,462.812500,79.710000,80.750000

In [51]:
tennessee_providers= providers[(providers['state_code_of_the_provider']=='TN')]
tennessee_providers.head(5)

,national_provider_identifier,last_name/organization_name_of_the_provider,first_name_of_the_provider,middle_initial_of_the_provider,credentials_of_the_provider,gender_of_the_provider,entity_type_of_the_provider,street_address_1_of_the_provider,street_address_2_of_the_provider,city_of_the_provider,...,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary/per_day_services,average_medicare_allowed_amount,average_submitted_charge_amount,average_medicare_payment_amount,average_medicare_standardized_amount
415,1003002254,WALGREEN CO.,NaN,NaN,NaN,NaN,O,5104 BOBBY HICKS HWY,NaN,GRAY,...,90653,Vaccine for influenza for injection into muscle,Y,53.0,53,53,40.468868,40.59,39.661132,39.661132
416,1003002254,WALGREEN CO.,NaN,NaN,NaN,NaN,O,5104 BOBBY HICKS HWY,NaN,GRAY,...,90662,Vaccine for influenza for injection into muscle,Y,95.0,95,95,40.590000,40.59,39.780000,39.780000
417,1003002254,WALGREEN CO.,NaN,NaN,NaN,NaN,O,5104 BOBBY HICKS HWY,NaN,GRAY,...,90670,Pneumococcal vaccine for injection into muscle,Y,18.0,18,18,190.066667,205.59,186.267778,186.267778
418,1003002254,WALGREEN CO.,NaN,NaN,NaN,NaN,O,5104 BOBBY HICKS HWY,NaN,GRAY,...,G0008,Administration of influenza virus vaccine,N,162.0,161,162,19.400000,19.40,19.010000,25.320000
419,1003002254,WALGREEN CO.,NaN,NaN,NaN,NaN,O,5104 BOBBY HICKS HWY,NaN,GRAY,...,G0009,Administration of pneumococcal vaccine,N,21.0,21,21,19.400000,19.40,19.010000,25.320000

In [52]:
#tennessee_providers_cities = tennessee_providers[(tennessee_providers.nppes_provider_city=='NASHVILLE')|
#(tennessee_providers.nppes_provider_city=='FRANKLIN')|(tennessee_providers.nppes_provider_city=='HENDERSONVILLE')
#(tennessee_providers.nppes_provider_city=='MURFREESBORO')]



tennessee_providers_cities = tennessee_providers[(tennessee_providers['city_of_the_provider']=='NASHVILLE')|
(tennessee_providers['city_of_the_provider']=='FRANKLIN')|(tennessee_providers['city_of_the_provider']=='HENDERSONVILLE')|
(tennessee_providers['city_of_the_provider']=='MURFREESBORO')|(tennessee_providers['city_of_the_provider']=='LEBANON')]


tennessee_providers_cities

,national_provider_identifier,last_name/organization_name_of_the_provider,first_name_of_the_provider,middle_initial_of_the_provider,credentials_of_the_provider,gender_of_the_provider,entity_type_of_the_provider,street_address_1_of_the_provider,street_address_2_of_the_provider,city_of_the_provider,...,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary/per_day_services,average_medicare_allowed_amount,average_submitted_charge_amount,average_medicare_payment_amount,average_medicare_standardized_amount
2395,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,20610,Aspiration and/or injection of large joint or ...,N,61.0,37,60,64.691967,268.032787,47.191311,54.860164
2396,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,27447,Repair of knee joint,N,26.0,23,26,1307.530385,4319.000000,1021.338846,1142.162692
2397,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,72170,"X-ray of pelvis, 1 or 2 views",N,65.0,65,65,29.410000,78.000000,21.150000,25.368308
2398,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,73502,"X-ray of hip with pelvis, 2-3 views",N,65.0,39,65,38.310000,114.000000,28.781692,31.684308
2399,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,73562,"X-ray of knee, 3 views",N,43.0,36,43,35.302326,107.441860,25.268372,28.054884
2400,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,73564,"X-ray of knee, 4 or more views",N,82.0,76,82,47.889024,144.609756,33.773415,39.246585
2401,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,77073,Imaging for bone length assessment,N,46.0,37,46,33.190000,112.000000,24.544348,27.881957
2402,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,99204,"New patient office or other outpatient visit, ...",N,57.0,57,57,155.310000,303.000000,101.799474,114.532632
2403,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,99205,"New patient office or other outpatient visit, ...",N,23.0,23,23,195.780000,378.000000,137.740000,161.359130
2404,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,99213,Established patient office or other outpatient...,N,53.0,43,53,69.080000,133.000000,48.109434,53.476415
2405,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,99214,Established patient office or other outpatient...,N,44.0,34,44,101.910000,197.000000,74.452273,79.894318
2406,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,NaN,NASHVILLE,...,J1030,"Injection, methylprednisolone acetate, 40 mg",Y,45.0,31,36,5.938444,10.000000,4.363778,4.744222
3848,1003019902,ACOSTA,LEALANI,M,MD,F,I,3601 TVC,NaN,NASHVILLE,...,99205,"New patient office or other outpatient visit, ...",N,30.0,30,30,161.870000,484.000000,113.047000,120.817000
3849,1003019902,ACOSTA,LEALANI,M,MD,F,I,3601 TVC,NaN,NASHVILLE,...,99205,"New patient office or other outpatient visit, ...",N,51.0,51,51,195.780000,484.000000,123.270392,136.952549
3850,1003019902,ACOSTA,LEALANI,M,MD,F,I,3601 TVC,NaN,NASHVILLE,...,99215,Established patient office or other outpatient...,N,75.0,56,75,106.980000,339.000000,74.553733,79.878667
3851,1003019902,ACOSTA,LEALANI,M,MD,F,I,3601 TVC,NaN,NASHVILLE,...,99215,Established patient office or other outpatient...,N,140.0,97,140,136.906286,339.000000,94.157286,102.486429
3852,1003019902,ACOSTA,LEALANI,M,MD,F,I,3601 TVC,NaN,NASHVILLE,...,99223,"Initial hospital inpatient care, typically 70 ...",N,15.0,15,15,195.030000,457.000000,152.900000,161.220000
5740,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,20550,"Injections of tendon sheath, ligament, or musc...",N,15.0,11,14,45.202000,183.000000,32.908000,36.927333
5741,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,20610,Aspiration and/or injection of large joint or ...,N,25.0,20,24,58.384800,281.880000,45.772400,50.812000
5742,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,73030,"X-ray of shoulder, minimum of 2 views",N,37.0,24,33,25.587838,98.000000,20.057838,22.651622
5743,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,73110,"X-ray of wrist, minimum of 3 views",N,40.0,22,38,31.660000,114.000000,22.958500,26.330750
5744,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,73130,"X-ray of hand, minimum of 3 views",N,20.0,16,17,27.590000,102.000000,19.830500,22.707000
5745,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,73140,"X-ray of fingers, minimum of 2 views",N,26.0,18,24,28.070000,96.000000,22.010000,25.050000
5746,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,99203,"New patient office or other outpatient visit, ...",N,100.0,100,100,98.540000,336.000000,70.911800,79.609400
5747,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,99212,Established patient office or other outpatient...,N,22.0,22,22,39.680000,134.000000,24.039545,27.737273
5748,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,99213,Established patient office or other outpatient...,N,119.0,77,119,67.010000,225.000000,47.185546,54.771092
5749,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,99223,"Initial hospital inpatient care, typically 70 ...",N,13.0,13,13,189.180000,661.000000,148.310000,161.220000
5750,1003031261,RUBRIGHT,JAMES,H,M.D.,M,I,345 23RD AVE N,SUITE 212,NASHVILLE,...,J1040,"Injection, methylprednisolone acetate, 80 mg",Y,44.0,33,39,11.270227,28.000000,8.092273,8.092273
8979,1003050972,LENTZ,ROBERT,J,M.D.,M,I,3601 THE VANDERBILT CLINIC,NaN,NASHVILLE,...,94010,Measurement and graphic recording of total and...,N,18.0,17,18,8.230000,37.000000,5.733333,6.490000
8980,1003050972,LENTZ,ROBERT,J,M.D.,M,I,3601 THE VANDERBILT CLINIC,NaN,NASHVILLE,...,94726,Determination of lung volumes using plethysmog...,N,14.0,14,14,12.100000,52.000000,8.812143,9.715000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9840368,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,99215,Established patient office or other outpatient...,N,80.0,72,80,140.899375,294.962500,90.073375,98.417500
9840369,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,99223,"Initial hospital inpatient care, typically 70 ...",N,231.0,218,231,209.183766,506.917749,160.275844,158.781039
9840370,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,99232,"Subsequent hospital inpatient care, typically ...",N,137.0,100,137,74.621095,181.459854,58.095839,56.989562
9840371,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,99233,"Subsequent hospital inpatient care, typically ...",N,305.0,185,305,107.596393,257.918033,82.966098,82.627213
9840372,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,99291,Critical care delivery critically ill or injur...,N,40.0,28,40,219.998000,461.800000,165.302500,170.646500
9840373,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,J0585,"Injection, onabotulinumtoxina, 1 unit",Y,5690.0,16,24,5.779742,17.000000,4.360617,4.569441
9840374,1992950166,KAMRAN,SHAZIA,NaN,M.D.,F,I,3443 DICKERSON PIKE,SUITE 580,NASHVILLE,...,J3301,"Injection, triamcinolone acetonide, not otherw...",Y,102.0,11,27,1.780490,5.009804,1.355294,1.411373
9842089,1992961841,ANGLUM,ABIGAIL,L,APN,F,I,3801 HILLSBORO RD,NaN,NASHVILLE,...,81002,"Urinalysis, manual test",N,16.0,12,16,3.500000,19.000000,3.430000,3.430000
9842090,1992961841,ANGLUM,ABIGAIL,L,APN,F,I,3801 HILLSBORO RD,NaN,NASHVILLE,...,99213,Established patient office or other outpatient...,N,71.0,57,71,58.720000,115.000000,34.330704,38.341408
9842091,1992961841,ANGLUM,ABIGAIL,L,APN,F,I,3801 HILLSBORO RD,NaN,NASHVILLE,...,99214,Established patient office or other outpatient...,N,31.0,25,31,86.620000,170.000000,56.004516,60.748065
9845169,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,90662,Vaccine for influenza for injection into muscle,Y,15.0,15,15,49.030000,93.000000,48.050000,48.050000
9845170,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,96372,Injection beneath the skin or into muscle for ...,N,27.0,11,25,23.730000,67.000000,13.088889,17.453704
9845171,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,99204,"New patient office or other outpatient visit, ...",N,27.0,27,27,155.310000,303.000000,92.824444,106.544815
9845172,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,99213,Established patient office or other outpatient...,N,68.0,43,68,69.080000,133.000000,42.142353,48.288382
9845173,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,99214,Established patient office or other outpatient...,N,120.0,71,120,101.910000,197.000000,60.628250,68.928000
9845174,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,G0008,Administration of influenza virus vaccine,N,15.0,15,15,23.730000,67.000000,23.260000,25.320000
9845175,1992978845,CHILDS,ADAM,M,M.D.,M,I,2933 MEDICAL CENTER PKWY,SUITE A,MURFREESBORO,...,G0439,"Annual wellness visit, includes a personalized...",N,27.0,27,27,109.980000,312.000000,107.780000,115.360000
9845862,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,90662,Vaccine for influenza for injection into muscle,Y,52.0,52,52,48.787308,93.000000,47.812308,47.812308
9845863,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,96372,Injection beneath the skin or into muscle for ...,N,14.0,11,14,23.730000,67.000000,18.203571,19.863571
9845864,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99213,Established patient office or other outpatient...,N,165.0,106,165,69.080000,133.000000,41.907515,46.739212
9845865,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99214,Established patient office or other outpatient...,N,127.0,79,127,101.910000,197.000000,72.067244,77.943307
9845866,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99223,"Initial hospital inpatient care, typically 70 ...",N,89.0,79,89,195.030000,374.000000,145.735281,157.424494
9845867,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99232,"Subsequent hospital inpatient care, typically ...",N,161.0,84,161,69.670000,135.000000,51.433727,56.036087
9845868,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99233,"Subsequent hospital inpatient care, typically ...",N,162.0,59,162,100.580000,193.000000,76.980988,82.700556
9845869,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,99238,"Hospital discharge day management, 30 minutes ...",N,46.0,42,46,68.215435,134.000000,53.472826,56.417391
9845870,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,G0008,Administration of influenza virus vaccine,N,52.0,52,52,23.730000,67.000000,23.260000,25.320000
9845871,1992985949,BECK,ROBERT,L,M.D,M,I,2400 PATTERSON ST,SUITE 400,NASHVILLE,...,G0439,"Annual wellness visit, includes a personalized...",N,91.0,91,91,109.980000,312.000000,107.780000,115.360000
9846016,1992987085,HORTON,SUSANNE,M,CRNA,F,I,1211 MEDICAL CENTER DR,NaN,NASHVILLE,...,00320,Anesthesia for procedure on esophagus and neck...,N,17.0,16,17,186.568824,2194.941176,146.270588,153.111765
9846017,1992987085,HORTON,SUSANNE,M,CRNA,F,I,1211 MEDICAL CENTER DR,NaN,NASHVILLE,...,00740,Anesthesia for procedure on gastrointestinal t...,N,61.0,58,60,76.923443,917.975410,60.307377,63.126557
9846018,1992987085,HORTON,SUSANNE,M,CRNA,F,I,1211 MEDICAL CENTER DR,NaN,NASHVILLE,...,00810,Anesthesia for procedure on lower intestine us...,N,42.0,42,42,83.992143,1002.416667,68.004524,71.220000

In [53]:
outpatient.head(5)

,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hrr,apc,apc_desc,beneficiaries,capc_services,average_total_submitted_charges,average_medicare_allowed_amount,average_medicare_payment_amount,outlier_services,average_medicare_outlier_amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [54]:
tennessee_outpatient_providers=outpatient[(outpatient['provider_state']=='TN')]
tennessee_outpatient_providers.head(5)

,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hrr,apc,apc_desc,beneficiaries,capc_services,average_total_submitted_charges,average_medicare_allowed_amount,average_medicare_payment_amount,outlier_services,average_medicare_outlier_amount
49863,440001,Unicoi County Memorial Hospital,Greenway Circle,Erwin,TN,37650,TN - Johnson City,8011,Comprehensive Observation Services,16.0,16,9972.38,1824.38,1453.57,0.0,0.0
49864,440002,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301,TN - Jackson,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,517.0,532,5914.08,1079.42,855.41,NaN,NaN
49865,440002,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301,TN - Jackson,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,60.0,62,10995.44,1884.60,1495.72,NaN,NaN
49866,440002,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301,TN - Jackson,5091,Level 1 Breast/Lymphatic Surgery and Related P...,68.0,70,11645.03,2164.58,1713.24,NaN,NaN
49867,440002,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301,TN - Jackson,5092,Level 2 Breast/Lymphatic Surgery and Related P...,72.0,73,18190.85,3883.46,3085.21,0.0,0.0

In [55]:
#tennessee_outpatient_cities = tennessee_outpatient[(tennessee_outpatient.provider_city=='Nashville')|
#(tennessee_outpatient.provider_city=='Hendersonville')|(tennessee_outpatient.provider_city=='Franklin')|
#(tennessee_outpatient.provider_city=='Murfreesboro')]



tennessee_outpatient_provider_city = tennessee_outpatient_providers[(tennessee_outpatient_providers['provider_city']=='Nashville')|
                                                (tennessee_outpatient_providers['provider_city']=='Hendersonville')|
                                                (tennessee_outpatient_providers['provider_city']=='Franklin')|
                                                (tennessee_outpatient_providers['provider_city']=='Murfreesboro')|
                                                (tennessee_outpatient_providers['provider_city']=='Lebanon')]
tennessee_outpatient_provider_city.head(5)

,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hrr,apc,apc_desc,beneficiaries,capc_services,average_total_submitted_charges,average_medicare_allowed_amount,average_medicare_payment_amount,outlier_services,average_medicare_outlier_amount
49925,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,77.0,82,16658.51,1135.49,898.36,0.0,0.0
49926,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,26.0,26,25117.07,2010.12,1601.55,0.0,0.0
49927,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5091,Level 1 Breast/Lymphatic Surgery and Related P...,19.0,20,28844.44,2244.90,1769.69,0.0,0.0
49928,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5092,Level 2 Breast/Lymphatic Surgery and Related P...,11.0,12,39405.18,4134.01,3293.76,0.0,0.0
49929,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5112,Level 2 Musculoskeletal Procedures,18.0,19,14518.82,1061.06,835.68,NaN,NaN

In [56]:
mid_tn_providers = tennessee_providers_cities.drop(columns=['middle_initial_of_the_provider','state_code_of_the_provider',
                                                              'country_code_of_the_provider','gender_of_the_provider',
                                                              'medicare_participation_indicator','street_address_2_of_the_provider'])

In [57]:
mid_tn_providers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54115 entries, 2395 to 9846018
Data columns (total 20 columns):
national_provider_identifier                                54115 non-null int64
last_name/organization_name_of_the_provider                 54115 non-null object
first_name_of_the_provider                                  51922 non-null object
credentials_of_the_provider                                 50653 non-null object
entity_type_of_the_provider                                 54115 non-null object
street_address_1_of_the_provider                            54115 non-null object
city_of_the_provider                                        54115 non-null object
zip_code_of_the_provider                                    54115 non-null object
provider_type                                               54115 non-null object
place_of_service                                            54115 non-null object
hcpcs_code                                                  54115 non-null object
hcpcs_description                                           54115 non-null object
hcpcs_drug_indicator                                        54115 non-null object
number_of_services                                          54115 non-null float64
number_of_medicare_beneficiaries                            54115 non-null int64
number_of_distinct_medicare_beneficiary/per_day_services    54115 non-null int64
average_medicare_allowed_amount                             54115 non-null float64
average_submitted_charge_amount                             54115 non-null float64
average_medicare_payment_amount                             54115 non-null float64
average_medicare_standardized_amount                        54115 non-null float64
dtypes: float64(5), int64(3), object(12)
memory usage: 8.7+ MB

In [61]:
# individual statements for filters
mid_tn_providers_43249 = mid_tn_providers.loc[
    (mid_tn_providers['entity_type_of_the_provider'] == 'O') &
    (mid_tn_providers['provider_type'] == 'Ambulatory Surgical Center')
   & (mid_tn_providers['hcpcs_code'] == '43249')
]

In [62]:
mid_tn_providers_43249

,national_provider_identifier,last_name/organization_name_of_the_provider,first_name_of_the_provider,credentials_of_the_provider,entity_type_of_the_provider,street_address_1_of_the_provider,city_of_the_provider,zip_code_of_the_provider,provider_type,place_of_service,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary/per_day_services,average_medicare_allowed_amount,average_submitted_charge_amount,average_medicare_payment_amount,average_medicare_standardized_amount
1272942,1124498357,ENDOSCOPY CENTER OF INLAND EMPIRE LLC,NaN,NaN,O,401 COMMERCE ST,NASHVILLE,372192446,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,N,16.0,16,16,660.990000,2200.00000,512.294375,484.535000
2185063,1225039761,ENDOSCOPY CENTER OF ST THOMAS LP,NaN,NaN,O,4230 HARDING RD,NASHVILLE,372052013,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,N,17.0,16,17,565.636471,1500.00000,435.024706,468.650588
6277101,1639299803,MURFREESBORO MEDICAL CLINIC P A,NaN,NaN,O,1272 GARRISON DR,MURFREESBORO,371292598,Ambulatory Surgical Center,F,43249,Balloon dilation of esophagus using an endoscope,N,33.0,32,33,587.110000,739.69697,433.111515,465.513939

In [63]:
# individual statements for filters
tennessee_outpatient_provider_city_5302 = tennessee_outpatient_provider_city.loc[
    tennessee_outpatient_provider_city['apc'] == 5302
]


tennessee_outpatient_provider_city_5302

,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hrr,apc,apc_desc,beneficiaries,capc_services,average_total_submitted_charges,average_medicare_allowed_amount,average_medicare_payment_amount,outlier_services,average_medicare_outlier_amount
49936,440006,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207,TN - Nashville,5302,Level 2 Upper GI Procedures,13.0,15,14899.44,1248.62,994.84,0.0,0.0
50148,440029,Williamson Medical Center,4321 Carothers Parkway,Franklin,TN,37067,TN - Nashville,5302,Level 2 Upper GI Procedures,16.0,18,5393.22,1248.62,994.84,0.0,0.0
50271,440039,Vanderbilt University Medical Center,1211 Medical Center Drive,Nashville,TN,37232,TN - Nashville,5302,Level 2 Upper GI Procedures,477.0,623,7120.82,1205.62,958.82,NaN,NaN
50429,440053,Saint Thomas Rutherford Hospital,1700 Medical Center Parkway,Murfreesboro,TN,37129,TN - Nashville,5302,Level 2 Upper GI Procedures,50.0,55,10690.86,1248.62,994.84,0.0,0.0
50662,440082,Saint Thomas West Hospital,"4220 Harding Rd, Po Box 380",Nashville,TN,37205,TN - Nashville,5302,Level 2 Upper GI Procedures,189.0,207,6350.16,1224.59,970.81,0.0,0.0
50793,440111,Metro Nashville General Hospital,1818 Albion Street,Nashville,TN,37208,TN - Nashville,5302,Level 2 Upper GI Procedures,11.0,12,4488.79,1248.62,994.84,0.0,0.0
50927,440133,Saint Thomas Midtown Hospital,2000 Church St,Nashville,TN,37236,TN - Nashville,5302,Level 2 Upper GI Procedures,76.0,98,8420.01,1238.47,984.69,NaN,NaN
51057,440161,Tristar Centennial Medical Center,2300 Patterson Street,Nashville,TN,37203,TN - Nashville,5302,Level 2 Upper GI Procedures,151.0,170,11861.73,1207.66,953.88,0.0,0.0
51257,440193,Tennova Healthcare-Lebanon,1411 Baddour Parkway,Lebanon,TN,37087,TN - Nashville,5302,Level 2 Upper GI Procedures,29.0,30,17455.66,1182.30,928.52,0.0,0.0
51275,440194,Tristar Hendersonville Medical Center,355 New Shackle Island Rd,Hendersonville,TN,37075,TN - Nashville,5302,Level 2 Upper GI Procedures,85.0,92,15882.34,1142.08,886.71,0.0,0.0
51289,440197,Tristar Southern Hills Medical Center,391 Wallace Rd,Nashville,TN,37211,TN - Nashville,5302,Level 2 Upper GI Procedures,44.0,49,20273.75,1228.34,973.60,0.0,0.0